#server
server:  port: 8080
  tomcat:    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 100
  servlet:    context-path: /

#spring
spring:  datasource:
    driver-class-name: com.mysql.jdbc.Driver    url: jdbc:mysql:///ebook?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  thymeleaf:
    prefix: /pages/    suffix: .html
  mvc:    view:      prefix: /pages/
      suffix: .html
 
#mybatis    
mybatis-plus:
  type-aliases-package: com.ec.pojo ##别包名,自动拼接全包名+类名  configuration:      default-statement-timeout: 30   #默认生命周期
    map-underscore-to-camel-case: true  #开启驼峰映射
  mapper-locations:  - classpath:/mapper/*/*.xml
  
#logging
logging:  level:   com.ec: debug
  
    
    